version: "3.5"
services:
  develop:
    build: .
    ports:
      - "4400:4400"
    container_name: forest-watcher-develop
    environment:
      PORT: 4400
      NODE_PATH: app/src
      NODE_ENV: dev
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CONTROL_TOWER_URL: https://api.resourcewatch.org
      LOCAL_URL: http://127.0.0.1:4400
      FORMS_API_URL: http://fw-forms-develop:4401/api/v1
      AREAS_API_URL: https://staging-api.resourcewatch.org
      GEOSTORE_API_URL: https://staging-api.resourcewatch.org
      API_VERSION: v1
    volumes:
      - ./app:/opt/forest-watcher/app
    networks:
      - gfw-fw-network
      - gfw-network
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js

  docs:
    build: .
    ports:
      - "44000:44000"
    container_name: forest-watcher-docs
    volumes:
      - ./docs:/opt/forest-watcher/docs
    command: yarn run docs -l 44000

networks:
  gfw-fw-network:
    name: gfw-fw-network
  gfw-network:
    name: gfw-network
