version: "3.5"
services:
  develop:
    build: .
    ports:
      - "4400:4400"
    container_name: forest-watcher-develop
    environment:
      PORT: 4400
      NODE_ENV: dev
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: fw_api_db
      CONTROL_TOWER_URL: https://staging-api.resourcewatch.org
      LOCAL_URL: http://127.0.0.1:4400
      FORMS_API_URL: https://staging-api.resourcewatch.org/v1
      AREAS_API_URL: https://staging-api.resourcewatch.org/v1
      GEOSTORE_API_URL: https://staging-api.resourcewatch.org/v1
      TEAMS_API_URL: "https://dev-fw-api.globalforestwatch.org/v3"
      API_VERSION: v1
    volumes:
      - ./app:/opt/forest-watcher/app
      - ./config:/opt/fw-service-template/config
      - ./nodemon.json:/opt/forest-watcher/nodemon.json
    networks:
      - gfw-fw-network
      - gfw-network
    command: yarn dev

  test:
    build: .
    container_name: forest-watcher-tests
    environment:
      PORT: 0
      NODE_ENV: test
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CONTROL_TOWER_URL: http://127.0.0.1:9000
      LOCAL_URL: http://127.0.0.1:4400
      FORMS_API_URL: http://127.0.0.1:9000
      AREAS_API_URL: http://127.0.0.1:9000
      GEOSTORE_API_URL: http://127.0.0.1:9000
      TEAMS_API_URL: "https://dev-fw-api.globalforestwatch.org/v3"
      API_VERSION: v1
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: fw_api_db
    volumes:
      - ./app:/opt/forest-watcher/app
      - ./nodemon.json:/opt/forest-watcher/nodemon.json
      - ./jest.config.js:/opt/forest-watcher/jest.config.js
    command: yarn test:jest --runInBand
    depends_on:
      - mongo
    networks:
      - gfw-fw-network
      - gfw-network

  mongo:
    image: mongo:3.6
    container_name: fw-api-mongo-develop
    ports:
      - "27025:27017"
    environment:
      MONGO_INITDB_DATABASE: fw_api_db
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - fw-api-mongodb-data:/data/db
    restart: always
    networks:
      - gfw-network

  docs:
    build: .
    ports:
      - "44000:44000"
    container_name: forest-watcher-docs
    volumes:
      - ./docs:/opt/forest-watcher/docs
    command: yarn run docs -l 44000

volumes:
  fw-api-mongodb-data:

networks:
  gfw-fw-network:
    name: gfw-fw-network
  gfw-network:
    name: gfw-network
